---

# common
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:

  - name: install git
    apt:
      name: git
      state: present
      update_cache: yes

# web
- hosts: web
  become: yes

  tasks:

  - name: install nginx
    apt:
      name: nginx
      state: present

  - name: write our nginx.conf
    template:
      src: /home/vagrant/examples/frontend_templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx

  - name: write our /etc/nginx/sites-available/default
    template:
      src: /home/vagrant/examples/frontend_templates/default-site.j2
      dest: /etc/nginx/sites-available/default
    notify: restart nginx

  - name: deploy website content
    template:
      src: /home/vagrant/examples/frontend_templates/index.html.j2
      dest: /usr/share/nginx/html/index.html

  handlers:

  - name: restart nginx
    service:
      name: nginx
      state: restarted

# lbal
- hosts: lb
  become: yes

  tasks:

  - name: install haproxy and socat
    apt:
      pkg: ['haproxy', 'socat']
      state: latest

  - name: enable haproxy
    lineinfile:
      path: /etc/default/haproxy
      regexp: "^ENABLED="
      line: ENABLED=1
    notify: restart haproxy

  - name: deploy haproxy config
    template:
      src: /home/vagrant/examples/frontend_templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:

  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
